# Generated by Django 5.0.4 on 2024-05-11 20:18

import django.db.models.deletion
import raffle.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.SlugField(blank=True, max_length=255, null=True)),
                ('scheduled_date', models.DateTimeField()),
                ('number_quantity', models.PositiveSmallIntegerField(choices=[(1, 100), (2, 200), (3, 500), (4, 1000), (5, 10000), (6, 1000000)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('google_tag_manage_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pixel_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_video_link', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=raffle.models.get_upload_path)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='outros', max_length=120)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.raffle')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='AwardedQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('more_popular', models.BooleanField(null=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.raffle')),
            ],
            options={
                'verbose_name_plural': 'Automatic Buys',
            },
        ),
    ]
