# Generated by Django 5.0.4 on 2024-05-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raffle',
            old_name='name',
            new_name='title',
        ),
    ]
