# Generated by Django 5.0.4 on 2024-05-01 14:34

import datetime
import django.db.models.deletion
import src.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.SlugField(blank=True, max_length=255, null=True)),
                ('scheduled_date', models.DateTimeField()),
                ('number_quantity', models.CharField(choices=[(1, 100), (2, 200), (3, 500), (4, 1000), (5, 10000), (6, 1000000)], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_quantity', models.IntegerField()),
                ('google_tag_manage_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pixel_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_video_link', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 1, 14, 34, 39, 280130, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name_plural': 'Raffles',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=src.models.get_upload_path)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='outros', max_length=120)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.raffle')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='AwardedQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('more_popular', models.BooleanField(null=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.raffle')),
            ],
            options={
                'verbose_name_plural': 'Automatic Buys',
            },
        ),
    ]
